services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: query-agent-web
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

      - WEAVIATE_URL=http://weaviate:8080
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      - weaviate
      - redis
    command: uvicorn src.main.chatbotapi:app --host 0.0.0.0 --port 8000

  weaviate:
    image: semitechnologies/weaviate:1.27.0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    restart: on-failure:0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always
